shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.home, name='home'),
    path('categories/', views.category_list, name='category_list'),
    path('search/', views.search_products, name='search_products'),
    path('about/', views.about, name='about'),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('products/<int:pk>/', views.product_detail_view,
         name='product-detail-view'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image_one = models.ImageField(upload_to='products/%Y/%m/%d',
                                  blank=True)
    image_two = models.ImageField(upload_to='products/%Y/%m/%d',
                                  blank=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ManyToManyField(
        Category, related_name="products")

    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.FloatField(default=0)
    size = models.IntegerField(default=1)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from shop.models import Category,   Product
from cart.forms import CartAddProductForm
from .serializers import ProductSerializer
from django.http import JsonResponse


def product_detail_view(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    related_products = Product.objects.filter(
        category__in=product.category.all()).exclude(id=product.id)

    context = {
        'product': product,
        'related_products': related_products}

    print('Productos Relacionados', related_products)

    return render(request, 'shop/product/detail.html', context)


def home(request):
    categories = Category.objects.all()
    products = Product.objects.filter(available=True).order_by('?')
    categories_side = Category.objects.all()
    categories = Category.objects.order_by('?')
    show_all = request.GET.get('show_all', False) == 'True'

    if show_all:
        categories = categories_side
    else:
        categories = categories[:6]
        products = products[:6]

    return render(request, 'shop/product/home.html',
                  {'categories': categories,
                   'products': products,
                   'show_all': show_all,
                   'categories_side': categories_side})


def category_list(request):
    categories = Category.objects.order_by('?')
    show_all = request.GET.get('show_all', False) == 'True'

    if not show_all:
        categories = categories[:6]

    print(categories)

    return render(request, 'shop/product/category_list.html',
                  {'categories': categories,
                   'show_all': show_all})


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True).order_by('?')

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    show_all = request.GET.get('show_all', False)

    if not show_all:
        products = products[:6]

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'show_all': show_all})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    related_products = Product.objects.filter(
        category__in=product.category.all()
    ).exclude(id=product.id)

    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'related_products': related_products,})


def search_products(request):
    search_term = ""
    if 'search' in request.GET:
        search_term = request.GET['search']
        products = Product.objects.filter(name__icontains=search_term)
    else:
        products = Product.objects.all()
    product_data = ProductSerializer(products, many=True).data

    return render(request,
                  'shop/product/searched.html',
                  {'products': products,
                   'search_term': search_term})


def about(request):
    return render(request, 'shop/product/about.html')

shop/templates/shop/product/about.html
{% extends 'shop/base.html' %} 
{% load static %}
 {% block content %}
<div class="container-about">
  <div class="titulo-about">
    <section class="py-5">
      <div class="container">
        <div class="row align-items-center gx-4">
          <div class="col-md-5">
            <div class="ms-md-2 ms-lg-5">
              <img class="img-fluid rounded-3" src="{% static 'media/picture_9.jpg' %}">
            </div>
          </div>
          <div class="col-md-6 offset-md-1">
            <div class="ms-md-2 ms-lg-5">
              <span class="text-muted">Nuestra Historia</span>
              <h2 class="display-5 fw-bold">Acerca de Almafuerte Ortopedia</h2>
              <p class="lead">
                En Almafuerte Ortopedias estamos al servicio de la salud y el bienestar desde hace más de 17 años. Ubicados en el centro de San Justo, nos especializamos en la venta y fabricación de productos ortopédicos adaptados a las necesidades de cada cliente.
              </p>
              <p class="lead mb-0">
                
                También ofrecemos una amplia selección de artículos deportivos diseñados para prevenir lesiones y apoyar procesos de recuperación. Nuestra misión es ayudarte a moverte mejor, recuperarte más rápido y alcanzar tus objetivos de bienestar con productos de alta calidad y atención personalizada.
                En Almafuerte, trabajamos con experiencia y dedicación para ser tu mejor aliado en salud y deporte. ¡Te esperamos!
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
{% endblock %}

shop/templates/shop/product/category_list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
  {% if category %}{{ category.name }}{% else %}Almafuerte{% endif %}
{% endblock %}
{% block content %}
       
  <div class="col-md-9">
        <div id="main" class="product-list-sold">
          <h1>{% if category %}{{ category.name }}{% else %}Todas las categorias{% endif %}</h1>
          <div class="all-products-sold">
            <div class="row">
              <div class="all-categories">
            <div class="row">
              {% for category in categories %}
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="card card-category">
                    <div class="card-image">
                      <a href="{{ category.get_absolute_url }}">
                        <img src="{% if category.image_one %}{{ category.image_one.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ category.name }}">
                      </a>
                    </div>
                    <div class="card text-center">
                      <a href="{{ category.get_absolute_url }}">
                        <h5 class="card-title ">{{ category.name }}</h5>
                      </a>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>              
          </div>        
        </div>       
      </div>                  
  </div>
{% endblock %}

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
  {{ product.name }}
{% endblock %}
{% block content %}
  <div class="container product-detail">
    <div class="row">
      <div class="col-md-6">
        <img class="img-fluid" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ product.name }}">
      </div>
      <div class="col-md-6">
        <h1>{{ product.name }}</h1>
        <h2>
          <ul>
            {% for category in product.category.all %}
                <li> <a href="{{ product.category.get_absolute_url }}">
                        {{ category.name }}
                      </a>
                </li>
              {% endfor %}
          </ul>
        </h2>
        <p class="price">${{ product.price }}</p>

        <div class=button-container>
          <form action="{% url "cart:cart_add" product.id %}" method="post" class="add-to-cart-form">
            {% csrf_token %}

            <div class="row-forms">
              <div class="form-group custom-form-group">
                <label class="quantity-label">{{ cart_product_form.quantity.label }}</label>
                {{ cart_product_form.quantity }}              
              </div>                      
              <div class="form-group custom-form-group">  
                <label class="size-label">{{ cart_product_form.size.label }}</label>
                  {{ cart_product_form.size}}
              </div>
                <input type="hidden" name="action" value="">
              </div>
            </div>

            <div class="row-forms">
              <button type="submit" class="btn button-buy btn-buy" onclick="this.form.action.value='buy_now'"> Comprar ahora</button>
              <button type="submit" class="btn btn-round" onclick="this.form.action.value='add_cart' ">Agregar al carrito</button>
            </div>

          </form>

        </div>


        </div>
        <p class="description">{{ product.description|linebreaks }}</p>
      </div>
      <hr>
      <div class="container mt-4">
        <div class="row text-center">
          
          <div class="col-12 col-sm-6 col-lg-3 mb-4">
            <div class="d-flex align-items-center justify-content-center">
              <i class="fa-solid fa-truck-fast fs-1  me-2"></i>
              <p class="mb-0">Envío</p>
            </div>
          </div>

          
          <div class="col-12 col-sm-6 col-lg-3 mb-4">
            <div class="d-flex align-items-center justify-content-center">
              <i class="fa-solid fa-credit-card fs-1  me-2"></i>
              <p class="mb-0">Tarjetas</p>
            </div>
          </div>

          
          <div class="col-12 col-sm-6 col-lg-3 mb-4">
            <div class="d-flex align-items-center justify-content-center">
              <i class="fa-solid fa-comments-dollar fs-1  me-2"></i>
              <p class="mb-0">Transferencia</p>
            </div>
          </div>

          
          <div class="col-12 col-sm-6 col-lg-3 mb-4">
            <div class="d-flex align-items-center justify-content-center">
              <i>
                <img src="{% static 'media/mp-icon.ico' %}" class="mp-icon" alt="Mercado Pago">
              </i>
              <p class="mb-0 ms-2">MP</p>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="related-product">
        <h4>Otros productos que podrian interesarte</h4>
        <section class="container pt-3">
          <section class="carousel-slide" data-bs-ride="carousel" id="postsCarousel">
            <div class="carousel-inner">
              {% if related_products %}
                {% for related_product in related_products %}
                  <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    
                    <div class="card h-100">
                      <div class="card-image">
                        <a href="{{ related_product.get_absolute_url }}">
                          {% if related_product.image %}
                            <img src="{{ related_product.image.url }}" alt="{{ related_product.name }}" class="img-fluid">
                          {% else %}
                          <img src="{% static 'products/tensiometro_aneroide.jpg' %}" alt="Imagen hardocodeada" class="img-fluid">
                          {% endif %}
                        </a>
                      </div>
                      <div class="card-body text-center">
                        <a href="{{ related_product.get_absolute_url }}">
                          <h5>{{ related_product.name }}</h5>
                        </a>
                      </div>
                      <div class="card-footer text-center">
                        <span>${{ related_product.price }}</span>
                      </div>
                    </div>
                  </div>
                {% endfor %}
              {% else %}
                <p>No se encontraron productos relacionados.</p>
              {% endif %}
            </div>      
              <a class="carousel-control-prev" href="#postsCarousel" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </a>
              <a class="carousel-control-next" href="#postsCarousel" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </a>
          </section>
        </section>
          <a  class="whats-app" href="https://api.whatsapp.com/send?phone=541156421409" target="_blank">
            <i class="fa-brands fa-whatsapp"></i>
          </a>
      </div>
{% endblock %} 

shop/templates/shop/product/home.html
{% extends "shop/base.html" %}
{% load static %}

{% if category %}{{ category.name }}{% else %}Almafuerte{% endif %}
  
{% block carousel %}
  
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'media/picture_1.jpg' %}" class="d-block w-100" alt="First slide">
        <div class="carousel-caption d-md-block">
          <h1 class="slide-title"> <img src="{% static 'media/Flamenco_logo.png' %}" alt="Logo" class="icon-logo">lmafuerte</h1>
          <h5 class="slide-sub">ORTOPEDIAS.</h5>        
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'media/picture_7.jpg' %}" class="d-block w-100" alt="Second slide">
        <div class="carousel-caption  d-md-block">
          <h1 class="slide-title"><img src="{% static 'media/Flamenco_logo.png' %}" alt="Logo" class="icon-logo">lmafuerte</h1>
          <h5 class="slide-sub">ORTOPEDIAS.</h5>
                    
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'media/picture_3.jpg' %}" class="d-block w-100" alt="Third slide">
        <div class="carousel-caption  d-md-block">
          <h1 class="slide-title-dif"> <img src="{% static 'media/Flamenco_logo.png' %}" alt="Logo" class="icon-logo">lmafuerte</h1>
          <h5 class="slide-sub">ORTOPEDIAS.</h5>          
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previo</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Siguiente</span>
    </button>
  </div>
{% endblock %}

{% block content %}
  <div class="mt-4">
    <div class="row">
      <div class="col-md-3">
      <h3>Categorias</h3>
        <div class="collapse-panel">
          <div id="sidebar">
            <div data-bs-spy="scroll" data-bs-smooth-scroll="true" class="scrollspy-example-2" tabindex="0">
              
              <ul class="card card-refine card-plain">
               <h6>
                <li class="card-title {% if not category %}active{% endif %}">
                  <a href="{% url "shop:product_list" %}" class="custom-card-link">Todos los productos</a>
                </li>
                {% for c in categories_side %}
                  <li class="card card-refine card-plain{% if category.slug == c.slug %}active{% endif %}">
                    <a href="{{ c.get_absolute_url }}" class="custom-card-link">{{ c.name }}</a>
                  </li>
                {% endfor %}
               </h6>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-9">
        <div id="main" class="product-list">
          <h1>Todo lo que buscas</h1>
          <div class="all-categories">
            <div class="row">
              {% for category in categories %}
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="card card-category">
                    <div class="card-image">
                      <a href="{{ category.get_absolute_url }}">
                        <img src="{% if category.image_one %}{{ category.image_one.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ category.name }}">
                      </a>
                    </div>
                    <div class="card text-center">
                      <a href="{{ category.get_absolute_url }}">
                        <h5 class="card-title ">{{ category.name }}</h5>
                      </a>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
            <div class="text-center mt-4">
                <a href="{% url 'shop:category_list' %}?show_all=True" class="btn btn-round">Cargar todas</a>
            </div>           
          </div>        
        </div>       
      </div>      
      <div class="container">
        <h2 class="section-title">Deportes</h2>
    </div> 
      <div class="projects-4">
          <div class="container-fluid">
              <div class="row">                  
                  <div class="col-md-6 px-0">
                      <div class="card card-fashion card-background" style="background-image: url('{% static "media/picture_4.jpg" %}');">
                        
                          <div class="card-body">
                              <div class="card-title">
                                  <h2>
                                      <a class="card-letters" href= "{% url 'shop:product_list_by_category' 'futbol' %}">
                                          Futbol, todo lo que necesitas para volver mas fuerte.
                                      </a>
                                  </h2>
                              </div>
                              <div class="card-footer text-left">
                                  
                                  <div class="stats">
                                      <span>
                                          <i class="now-ui-icons users_circle-08"></i> 
                                      <span>
                                          <i class="now-ui-icons tech_watch-time"></i> 
                                      </span>
                                  </div>
                                  <div class="stats-link pull-right">
                                      <a href="#pablo" class="footer-link"></a>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                                  
                  <div class="col-md-6 px-0">
                      <div class="card-container">
                          
                          <div class="card card-fashion">
                              
                              <div class="card-title">
                                  <h4>
                                      <a class="card-letters1" href="{% url 'shop:product_list_by_category' 'gym-training' %}">
                                      Training, transforma tu esfuerzo en resultados.</a>
                                  </h4>
                              </div>
                              <div class="card-body">
                                  <div class="card-footer text-left">
                                      <div class="stats">
                                          <span>
                                              <i class="now-ui-icons users_circle-08"></i> 
                                          </span>
                                          <span>
                                              <i class="now-ui-icons tech_watch-time"></i> 
                                          </span>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div class="card card-fashion card-background" style="background-image: url('{% static "media/picture_11.jpg" %}');">
                          </div>
                      </div>
                  </div>
              </div>
          </div>
    </div>
  <div class="col-md-9">
        <div id="main" class="product-list-sold">
          <h1>{% if category %}{{ category.name }}{% else %}Lo más vendido{% endif %}</h1>
          <div class="all-products-sold">
            <div class="row">
              {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="card card-product">
                    <div class="card-image">
                      <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ product.name }}">
                      </a>
                    </div>
                    <div class="card text-center">
                      <a href="{{ product.get_absolute_url }}">
                        <h5 class="card-title ">{{ product.name }}</h5>
                      </a>
                      <div class="card-footer-center">
                        <div class="price-container">
                          <span class="price">${{ product.price }}</span>
                        </div>                      
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
            <div class="text-center mt-4">
                <a href="{% url 'shop:product_list' %}?show_all=True"  class="btn btn-round">Cargar más..</a>
            </div>
          </div>        
        </div>       
      </div>
      <div class="projects-4">
          <div class="container-fluid">
              <div class="row">
                  
                  <div class="col-md-6 px-0">
                      <div class="card card-fashion card-background" style="background-image: url('{% static "media/paddle-tennis.jpg" %}');">
                        
                          <div class="card-body">
                              <div class="card-title-tenis">
                                  <h2>
                                      <a class="card-letters2" href= "{% url 'shop:product_list_by_category' 'tenis-paddle' %}">
                                          Equipamiento de alto rendimiento para cada golpe.
                                      </a>
                                  </h2>
                              </div>
                              <div class="card-footer text-left">
                                  
                                  <div class="stats">
                                      <span>
                                          <i class="now-ui-icons users_circle-08"></i> 
                                      <span>
                                          <i class="now-ui-icons tech_watch-time"></i> 
                                      </span>
                                  </div>
                                  <div class="stats-link pull-right">
                                      <a href="" class="footer-link"></a>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                                  
                  <div class="col-md-6 px-0">
                      <div class="card-container">
                          
                          <div class="card card-fashion">
                              
                              <div class="card-title">
                                  <h4>
                                      <a class="card-letters1" href="{% url 'shop:product_list_by_category' 'natacion' %}">
                                      Natación, convierte cada brazada en un nuevo logro.</a>
                                  </h4>
                              </div>
                              <div class="card-body">
                                  <div class="card-footer text-left">
                                      <div class="stats">
                                          <span>
                                              <i class="now-ui-icons users_circle-08"></i> 
                                          </span>
                                          <span>
                                              <i class="now-ui-icons tech_watch-time"></i> 
                                          </span>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          <div class="card card-fashion card-background" style="background-image: url('{% static "media/swimmer.jpg" %}');">
                          </div>
                      </div>
                  </div>
              </div>
          </div>
  </div>
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
  {% if category %}{{ category.name }}{% else %}Almafuerte{% endif %}
{% endblock %}
{% block content %}
       
  <div class="col-md-9">
        <div id="main" class="product-list-sold">
          <h1>{% if category %}{{ category.name }}{% else %}Lo más vendido{% endif %}</h1>
          <div class="all-products-sold">
            <div class="row">
              {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="card card-product">
                    <div class="card-image">
                      <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ product.name }}">
                      </a>
                    </div>
                    <div class="card text-center">
                      <a href="{{ product.get_absolute_url }}">
                        <h5 class="card-title ">{{ product.name }}</h5>
                      </a>
                      <div class="card-footer-center">
                        <div class="price-container">
                          <span class="price">${{ product.price }}</span>
                        </div>                      
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
            <div class="text-center mt-4">
                <a href="{% if category %}{% url 'shop:product_list_by_category' category.slug %}?show_all=True{% else %}{% url 'shop:product_list' %}?show_all=True{% endif %}" class="btn btn-round">Cargar mas..</a>
            </div>
          </div>        
        </div>       
      </div>
  </div>
{% endblock %}

shop/templates/shop/product/searched.html
{% extends "shop/base.html" %} 
{% load static %} 
{% block title %} 
{% if search_term %}Resultados de búsqueda para "{{ search_term }}"
{% else %}Resultados de búsqueda{% endif %} {% endblock %} {% block content %}
<div class="searched-title">
  <h1>ESTOS SON LOS PRODUCTOS Para "{{ search_term }}"</h1>
</div>
<div class="searched-products">
  <div class="col-md-9">
        <div id="main" class="product-list">
          <div class="all-products">
            <div class="row">
              {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                  <div class="card card-product card-plain">
                    <div class="card-image">
                      <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ product.name }}">
                      </a>
                    </div>
                    <div class="card text-center">
                      <a href="{{ product.get_absolute_url }}">
                        <h5 class="card-title ">{{ product.name }}</h5>
                      </a>
                      <div class="card-footer-center">
                        <div class="price-container">
                          <span class="price">${{ product.price }}</span>
                        </div>                      
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>        
        </div>       
      </div>
</div>
{% endblock %}